AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'storage/**/*'
    - 'docker/**/*'
    - 'scripts/**/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'current/**/*'
    - 'node_modules/**/*'
Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false